### ISSUE TITLE
Root Bone Inversion

### ISSUE THREAD

**Issue by Xifime** [halfuwu/UEFormat#6]
Please add a feature that was in ActorX importers to Blender labeled as "Don't invert Root Bone". Basically everything it was doing is just preventing model from turning upside down when Animation or anything else that could do the same is imported.

![image](https://github.com/halfuwu/UEFormat/assets/123459044/49c0fe1a-ce45-4a27-8fd1-4166df057c3e)

**Comment by halfuwu** [comment]
the root bone doesnt get inverted for ueformat though, it's just imported as is. are you saying you need it so you can disable it?

please send the .uemodel and .ueanim here so i can do some testing

**Comment by Xifime** [comment]
> the root bone doesnt get inverted for ueformat though, it's just imported as is. are you saying you need it so you can invert the root bone?
> 
> please send the .uemodel and .ueanim here so i can do some testing

Yes, just to automatically swap the root bone.

https://drive.google.com/drive/folders/1bHNqxh6SFxhRXSUXng7JU-hF8805bluJ?usp=sharing

**Comment by halfuwu** [comment]
i may be stupid but it seems you're importing a .psa on a .uemodel which is most likely causing the root inversions, could you please export the .ueanim and see if it works that way? if not, also send that here

**Comment by halfuwu** [comment]
and even if i do import the psa, it seems to be working fine
![image](https://github.com/halfuwu/UEFormat/assets/69497698/ec5ed48a-f053-4779-94aa-0fc1dcf88c32)

**Comment by Xifime** [comment]
> i may be stupid but it seems you're importing a .psa on a .uemodel which is most likely causing the root inversions, could you please export the .ueanim and see if it works that way? if not, also send that here

I use UEAnim and it still inverts for some unknown reasons, same to psa.

**Comment by halfuwu** [comment]
fixed the need to add this toggle at all, updated in latest commit

https://github.com/halfuwu/UEFormat/assets/69497698/12fa082d-08e9-4132-bf62-b59b8d245641
