### ISSUE TITLE
Failure to rebuild project on UE5.4.2, UE5.3.2, UE5.2.1

### ISSUE THREAD

**Issue by Voulqy** [halfuwu/UEFormat#8]
I've tried making Blueprint and C++ projects on 5.4.2, 5.3.2, and 5.2.1, and whenever I try opening the project, I get the expected error:
![err1](https://github.com/halfuwu/UEFormat/assets/47714156/959c2291-cb13-4552-bdc5-5ff82ddbb5a7)
![err2](https://github.com/halfuwu/UEFormat/assets/47714156/a34444e3-234e-456e-8f54-587ef3db053e)

So when I try cleaning and rebuilding the project in Visual Studio, it results in this same error, no matter what UE5 version used. 

![err](https://github.com/halfuwu/UEFormat/assets/47714156/3dfa2e55-f7d0-4ac8-b3cd-0ea58f42c2e5)

**Comment by halfuwu** [comment]
To be fair it is an easy fix, just give the animation import options enum a different name that doesnt conflict with the engine name.

@Ka1serM still should be fixed

**Comment by halfuwu** [comment]
fixed by https://github.com/halfuwu/UEFormat/commit/d079aa7f9150bae79ac1d5ced97b7af1354b2244
