### ISSUE TITLE
broken animation after importing from fmodel to UE 5.4?

### ISSUE THREAD

**Issue by M-U-X** [halfuwu/UEFormat#9]
[Models.zip](https://github.com/user-attachments/files/16430376/Models.zip)
using the latest UE version, Fmodel(QA) & UEformat, I exported the following mesh:
Valorant: ShooterGame/Content/Characters/Vampire/S0/3P/Models/TP_Vampire_S0_Skelmesh.uasset
& the following animations:
ShooterGame/Content/Characters/_Core/3P/Anims/TP_Core_WalkN_LB.uasset
ShooterGame/Content/Characters/_Core/3P/Anims/TP_Core_WalkAddN_UB.uasset

the mesh gets imported just fine, but the animations look broken:
![image](https://github.com/user-attachments/assets/ea21e206-b1d1-4013-ae94-0c8f44d1abdf)
![image](https://github.com/user-attachments/assets/4ed267ac-b68c-4a30-82d2-158209a1012b)
![image](https://github.com/user-attachments/assets/7441be0f-4696-41e5-872b-5f908ff3bbd5)

files attached

**Comment by M-U-X** [comment]
update: I installed the blender 4 importer today and imported the same files -same model and animation- and it's showing fine in blender no issues or mesh distortions of any kind, which would indicate that the issue probably lies within the UE 4 importer/plugin

**Comment by M-U-X** [comment]
@halfuwu any progress? or confirmation if it's the UE plugin?

**Comment by halfuwu** [comment]
it is confirmed that it's a ue plugin issue and neither of us have gotten to working on it

**Comment by halfuwu** [comment]
https://github.com/halfuwu/UEFormat/commit/058d37c95b1fe385215fbdf63eeb0ef049272c0b
